spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password:
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
server:
  servlet:
      context-path: /order
logging:
  level:
    org:
      springframework: info
kdt:
  version: "default-v1.0"
  minimum-order-amount: 1
  support-vendors:
        - default-a
        - default-b
  description: |-
    default line 1 hello world
    default line 2 xxxx
    default line 3

